# Generated by Django 4.1.1 on 2022-09-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kositeriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='detail',
            field=models.CharField(max_length=100, null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='detail',
            field=models.CharField(max_length=100, null=True, verbose_name='detail'),
        ),
    ]
