# Generated by Django 4.1.1 on 2022-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kositeriaApp', '0002_alter_deudas_detail_alter_gastos_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='cajaMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('month', models.TextField(verbose_name='month')),
                ('totalSold', models.BigIntegerField(verbose_name='totalSold')),
            ],
        ),
    ]
