# Generated by Django 4.1.1 on 2022-09-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kositeriaApp', '0003_cajamensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajamensual',
            name='year',
            field=models.BigIntegerField(default=2022, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='cajamensual',
            name='month',
            field=models.BigIntegerField(verbose_name='month'),
        ),
    ]
